2025-01-18 13:05:04 - __main__ - INFO - Testing database connection...
2025-01-18 13:05:04 - app.db.test_connection - ERROR - Error connecting to the database: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "your_username"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 13:05:04 - __main__ - ERROR - Database connection test failed!
2025-01-18 13:17:38 - __main__ - INFO - Testing database connection...
2025-01-18 13:17:38 - app.db.test_connection - ERROR - Error connecting to the database: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "your_username"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 13:17:38 - __main__ - ERROR - Database connection test failed!
2025-01-18 13:26:57 - __main__ - INFO - Testing database connection...
2025-01-18 13:26:57 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2025-01-18 13:26:57 - sqlalchemy.engine.Engine - INFO - [raw sql] {}
2025-01-18 13:26:57 - sqlalchemy.engine.Engine - INFO - select current_schema()
2025-01-18 13:26:57 - sqlalchemy.engine.Engine - INFO - [raw sql] {}
2025-01-18 13:26:57 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2025-01-18 13:26:57 - sqlalchemy.engine.Engine - INFO - [raw sql] {}
2025-01-18 13:26:57 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-01-18 13:26:57 - sqlalchemy.engine.Engine - INFO - SELECT 1
2025-01-18 13:26:57 - sqlalchemy.engine.Engine - INFO - [generated in 0.00098s] {}
2025-01-18 13:26:57 - app.db.test_connection - INFO - Successfully connected to the database!
2025-01-18 13:26:57 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-01-18 13:26:57 - __main__ - INFO - Database connection test passed!
